2025-03-09 20:08:08,083 INFO    Thread-42 (_run_job):134440 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 20:08:08,083 INFO    Thread-42 (_run_job):134440 [wandb_setup.py:_flush():67] Configure stats pid to 134440
2025-03-09 20:08:08,083 INFO    Thread-42 (_run_job):134440 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-09 20:08:08,084 INFO    Thread-42 (_run_job):134440 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-09 20:08:08,084 INFO    Thread-42 (_run_job):134440 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 20:08:08,084 INFO    Thread-42 (_run_job):134440 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250309_200808-s00buv1j/logs/debug.log
2025-03-09 20:08:08,084 INFO    Thread-42 (_run_job):134440 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250309_200808-s00buv1j/logs/debug-internal.log
2025-03-09 20:08:08,085 INFO    Thread-42 (_run_job):134440 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x70fd107dc080>
2025-03-09 20:08:08,085 INFO    Thread-42 (_run_job):134440 [wandb_init.py:init():761] calling init triggers
2025-03-09 20:08:08,085 INFO    Thread-42 (_run_job):134440 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 64, 'epochs': 15, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'rmsprop', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 20:08:08,085 INFO    Thread-42 (_run_job):134440 [wandb_init.py:init():784] starting backend
2025-03-09 20:08:08,085 INFO    Thread-42 (_run_job):134440 [wandb_init.py:init():788] sending inform_init request
2025-03-09 20:08:08,088 INFO    Thread-42 (_run_job):134440 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-09 20:08:08,088 INFO    Thread-42 (_run_job):134440 [wandb_init.py:init():803] backend started and connected
2025-03-09 20:08:08,090 INFO    Thread-42 (_run_job):134440 [wandb_run.py:_config_callback():1261] config_cb None None {'activation_function': 'relu', 'batch_size': 64, 'epochs': 15, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'rmsprop', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
2025-03-09 20:08:08,093 INFO    Thread-42 (_run_job):134440 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 20:08:08,111 INFO    Thread-42 (_run_job):134440 [wandb_init.py:init():896] updated telemetry
2025-03-09 20:08:08,121 INFO    Thread-42 (_run_job):134440 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-09 20:08:09,003 INFO    Thread-42 (_run_job):134440 [wandb_init.py:init():995] starting run threads in backend
2025-03-09 20:08:09,166 INFO    Thread-42 (_run_job):134440 [wandb_run.py:_console_start():2377] atexit reg
2025-03-09 20:08:09,167 INFO    Thread-42 (_run_job):134440 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 20:08:09,167 INFO    Thread-42 (_run_job):134440 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 20:08:09,167 INFO    Thread-42 (_run_job):134440 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-09 20:08:09,168 INFO    Thread-42 (_run_job):134440 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-09 23:00:25,599 INFO    MainThread:134440 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 23:00:25,600 INFO    MainThread:134440 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 23:00:50,358 INFO    MainThread:134440 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-09 23:00:51,171 INFO    MainThread:134440 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=200
2025-03-09 23:00:51,974 WARNING MsgRouterThr:134440 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-09 23:00:51,978 INFO    MsgRouterThr:134440 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
2025-03-09 23:01:00,361 INFO    MainThread:134440 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 23:01:00,361 INFO    MainThread:134440 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 23:01:06,826 INFO    MainThread:134440 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-09 23:01:07,892 INFO    MainThread:134440 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=250
2025-03-09 23:01:09,299 INFO    Thread-48 (_run_job):134440 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 23:01:09,299 INFO    Thread-48 (_run_job):134440 [wandb_setup.py:_flush():67] Configure stats pid to 134440
2025-03-09 23:01:09,299 INFO    Thread-48 (_run_job):134440 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-09 23:01:09,299 INFO    Thread-48 (_run_job):134440 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-09 23:01:09,300 INFO    Thread-48 (_run_job):134440 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 23:01:09,300 INFO    Thread-48 (_run_job):134440 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250309_230109-7xy6u92u/logs/debug.log
2025-03-09 23:01:09,300 INFO    Thread-48 (_run_job):134440 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250309_230109-7xy6u92u/logs/debug-internal.log
2025-03-09 23:01:09,300 INFO    Thread-48 (_run_job):134440 [wandb_init.py:init():761] calling init triggers
2025-03-09 23:01:09,301 INFO    Thread-48 (_run_job):134440 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 16, 'epochs': 15, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 23:01:09,301 INFO    Thread-48 (_run_job):134440 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 23:01:09,301 ERROR   Thread-48 (_run_job):134440 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 23:01:09,338 INFO    Thread-48 (_run_job):134440 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/s00buv1j
2025-03-09 23:01:14,070 INFO    Thread-42 (_run_job):134440 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/s00buv1j
2025-03-09 23:01:17,090 INFO    MainThread:134440 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 23:01:17,091 INFO    MainThread:134440 [wandb_init.py:_pause_backend():564] pausing backend
