2025-02-28 16:20:41,325 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:20:41,327 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:20:41,328 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:20:41,329 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:20:41,330 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:20:41,331 INFO    Thread-146 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162041-z9vxru34/logs/debug.log
2025-02-28 16:20:41,331 INFO    Thread-146 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162041-z9vxru34/logs/debug-internal.log
2025-02-28 16:20:41,332 INFO    Thread-146 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:20:41,333 INFO    Thread-146 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:20:41,333 INFO    Thread-146 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:20:41,334 ERROR   Thread-146 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:20:41,338 INFO    Thread-146 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:20:42,471 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:20:42,473 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:20:42,475 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:20:42,476 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:20:42,477 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:20:42,477 INFO    Thread-147 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162042-hdupjbre/logs/debug.log
2025-02-28 16:20:42,478 INFO    Thread-147 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162042-hdupjbre/logs/debug-internal.log
2025-02-28 16:20:42,479 INFO    Thread-147 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:20:42,479 INFO    Thread-147 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 4, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:20:42,480 INFO    Thread-147 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:20:42,481 ERROR   Thread-147 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:20:42,485 INFO    Thread-147 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:20:52,523 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:20:52,524 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:20:52,525 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:20:52,526 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:20:52,526 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:20:52,527 INFO    Thread-148 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162052-l99lelfm/logs/debug.log
2025-02-28 16:20:52,528 INFO    Thread-148 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162052-l99lelfm/logs/debug-internal.log
2025-02-28 16:20:52,529 INFO    Thread-148 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:20:52,529 INFO    Thread-148 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:20:52,530 INFO    Thread-148 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:20:52,531 ERROR   Thread-148 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:20:52,535 INFO    Thread-148 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:20:53,950 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:20:53,951 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:20:53,952 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:20:53,953 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:20:53,954 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:20:53,954 INFO    Thread-149 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162053-5ohubwwi/logs/debug.log
2025-02-28 16:20:53,955 INFO    Thread-149 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162053-5ohubwwi/logs/debug-internal.log
2025-02-28 16:20:53,955 INFO    Thread-149 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:20:53,956 INFO    Thread-149 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:20:53,957 INFO    Thread-149 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:20:53,957 ERROR   Thread-149 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:20:53,961 INFO    Thread-149 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:03,984 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:03,986 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:03,987 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:03,989 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:03,991 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:03,993 INFO    Thread-150 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162103-stubywf6/logs/debug.log
2025-02-28 16:21:03,994 INFO    Thread-150 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162103-stubywf6/logs/debug-internal.log
2025-02-28 16:21:03,996 INFO    Thread-150 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:03,997 INFO    Thread-150 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:21:03,997 INFO    Thread-150 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:03,998 ERROR   Thread-150 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:04,003 INFO    Thread-150 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:05,119 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:05,121 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:05,122 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:05,124 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:05,125 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:05,127 INFO    Thread-151 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162105-ivbsb743/logs/debug.log
2025-02-28 16:21:05,128 INFO    Thread-151 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162105-ivbsb743/logs/debug-internal.log
2025-02-28 16:21:05,129 INFO    Thread-151 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:05,129 INFO    Thread-151 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:21:05,130 INFO    Thread-151 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:05,131 ERROR   Thread-151 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:05,134 INFO    Thread-151 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:15,154 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:15,156 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:15,157 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:15,159 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:15,161 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:15,162 INFO    Thread-152 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162115-l1shtv9b/logs/debug.log
2025-02-28 16:21:15,164 INFO    Thread-152 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162115-l1shtv9b/logs/debug-internal.log
2025-02-28 16:21:15,165 INFO    Thread-152 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:15,167 INFO    Thread-152 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:21:15,167 INFO    Thread-152 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:15,168 ERROR   Thread-152 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:15,171 INFO    Thread-152 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:16,271 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:16,273 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:16,276 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:16,278 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:16,279 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:16,281 INFO    Thread-153 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162116-go1ugzmr/logs/debug.log
2025-02-28 16:21:16,282 INFO    Thread-153 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162116-go1ugzmr/logs/debug-internal.log
2025-02-28 16:21:16,282 INFO    Thread-153 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:16,283 INFO    Thread-153 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:21:16,284 INFO    Thread-153 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:16,284 ERROR   Thread-153 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:16,288 INFO    Thread-153 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:26,314 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:26,316 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:26,319 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:26,320 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:26,321 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:26,322 INFO    Thread-154 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162126-gg05qhe6/logs/debug.log
2025-02-28 16:21:26,322 INFO    Thread-154 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162126-gg05qhe6/logs/debug-internal.log
2025-02-28 16:21:26,323 INFO    Thread-154 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:26,324 INFO    Thread-154 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:21:26,324 INFO    Thread-154 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:26,325 ERROR   Thread-154 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:26,329 INFO    Thread-154 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
