2025-03-17 21:42:34,863 INFO    Thread-35 (_run_job):148851 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-17 21:42:34,863 INFO    Thread-35 (_run_job):148851 [wandb_setup.py:_flush():67] Configure stats pid to 148851
2025-03-17 21:42:34,863 INFO    Thread-35 (_run_job):148851 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-17 21:42:34,863 INFO    Thread-35 (_run_job):148851 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-17 21:42:34,863 INFO    Thread-35 (_run_job):148851 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 21:42:34,864 INFO    Thread-35 (_run_job):148851 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250317_214234-6d4vlz9z/logs/debug.log
2025-03-17 21:42:34,864 INFO    Thread-35 (_run_job):148851 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250317_214234-6d4vlz9z/logs/debug-internal.log
2025-03-17 21:42:34,864 INFO    Thread-35 (_run_job):148851 [wandb_init.py:init():761] calling init triggers
2025-03-17 21:42:34,864 INFO    Thread-35 (_run_job):148851 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-17 21:42:34,864 INFO    Thread-35 (_run_job):148851 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-17 21:42:34,864 ERROR   Thread-35 (_run_job):148851 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 21:42:34,873 INFO    Thread-35 (_run_job):148851 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/64a2ha4n
2025-03-17 21:42:36,195 INFO    Thread-30 (_run_job):148851 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/64a2ha4n
2025-03-17 21:42:44,937 INFO    Thread-37 (_run_job):148851 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-17 21:42:44,937 INFO    Thread-37 (_run_job):148851 [wandb_setup.py:_flush():67] Configure stats pid to 148851
2025-03-17 21:42:44,937 INFO    Thread-37 (_run_job):148851 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-17 21:42:44,937 INFO    Thread-37 (_run_job):148851 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-17 21:42:44,938 INFO    Thread-37 (_run_job):148851 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 21:42:44,938 INFO    Thread-37 (_run_job):148851 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250317_214244-ukhbgeom/logs/debug.log
2025-03-17 21:42:44,938 INFO    Thread-37 (_run_job):148851 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250317_214244-ukhbgeom/logs/debug-internal.log
2025-03-17 21:42:44,939 INFO    Thread-37 (_run_job):148851 [wandb_init.py:init():761] calling init triggers
2025-03-17 21:42:44,939 INFO    Thread-37 (_run_job):148851 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-17 21:42:44,939 INFO    Thread-37 (_run_job):148851 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-17 21:42:44,940 ERROR   Thread-37 (_run_job):148851 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 21:42:44,957 INFO    Thread-37 (_run_job):148851 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/64a2ha4n
2025-03-17 21:42:46,453 INFO    Thread-38 (_run_job):148851 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-17 21:42:46,453 INFO    Thread-38 (_run_job):148851 [wandb_setup.py:_flush():67] Configure stats pid to 148851
2025-03-17 21:42:46,454 INFO    Thread-38 (_run_job):148851 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-17 21:42:46,454 INFO    Thread-38 (_run_job):148851 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-17 21:42:46,454 INFO    Thread-38 (_run_job):148851 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 21:42:46,455 INFO    Thread-38 (_run_job):148851 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250317_214246-hcu5bd0j/logs/debug.log
2025-03-17 21:42:46,455 INFO    Thread-38 (_run_job):148851 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250317_214246-hcu5bd0j/logs/debug-internal.log
2025-03-17 21:42:46,456 INFO    Thread-38 (_run_job):148851 [wandb_init.py:init():761] calling init triggers
2025-03-17 21:42:46,456 INFO    Thread-38 (_run_job):148851 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'sgd', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-17 21:42:46,456 INFO    Thread-38 (_run_job):148851 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-17 21:42:46,457 ERROR   Thread-38 (_run_job):148851 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-17 21:42:46,473 INFO    Thread-38 (_run_job):148851 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/64a2ha4n
2025-03-17 21:42:54,081 INFO    MainThread:148851 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-17 21:42:54,082 INFO    MainThread:148851 [wandb_init.py:_pause_backend():564] pausing backend
