2025-02-28 12:04:44,222 INFO    Thread-106 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 12:04:44,225 INFO    Thread-106 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 12:04:44,228 INFO    Thread-106 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 12:04:44,231 INFO    Thread-106 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 12:04:44,232 INFO    Thread-106 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 12:04:44,234 INFO    Thread-106 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_120444-ew6pkhnl/logs/debug.log
2025-02-28 12:04:44,235 INFO    Thread-106 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_120444-ew6pkhnl/logs/debug-internal.log
2025-02-28 12:04:44,237 INFO    Thread-106 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 12:04:44,238 INFO    Thread-106 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'random_normal'}
config: {'_wandb': {}}
2025-02-28 12:04:44,239 INFO    Thread-106 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 12:04:44,241 ERROR   Thread-106 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 12:04:44,249 INFO    Thread-106 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 12:04:54,294 INFO    Thread-107 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 12:04:54,296 INFO    Thread-107 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 12:04:54,297 INFO    Thread-107 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 12:04:54,298 INFO    Thread-107 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 12:04:54,300 INFO    Thread-107 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 12:04:54,301 INFO    Thread-107 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_120454-p1bw90t1/logs/debug.log
2025-02-28 12:04:54,304 INFO    Thread-107 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_120454-p1bw90t1/logs/debug-internal.log
2025-02-28 12:04:54,309 INFO    Thread-107 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 12:04:54,315 INFO    Thread-107 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'glorot_uniform'}
config: {'_wandb': {}}
2025-02-28 12:04:54,319 INFO    Thread-107 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 12:04:54,324 ERROR   Thread-107 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 12:04:54,347 INFO    Thread-107 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 12:04:55,503 INFO    Thread-108 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 12:04:55,508 INFO    Thread-108 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 12:04:55,511 INFO    Thread-108 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 12:04:55,514 INFO    Thread-108 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 12:04:55,516 INFO    Thread-108 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 12:04:55,517 INFO    Thread-108 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_120455-bjb79vt2/logs/debug.log
2025-02-28 12:04:55,518 INFO    Thread-108 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_120455-bjb79vt2/logs/debug-internal.log
2025-02-28 12:04:55,520 INFO    Thread-108 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 12:04:55,521 INFO    Thread-108 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'glorot_uniform'}
config: {'_wandb': {}}
2025-02-28 12:04:55,522 INFO    Thread-108 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 12:04:55,523 ERROR   Thread-108 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 12:04:55,532 INFO    Thread-108 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 12:05:05,577 INFO    Thread-109 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 12:05:05,580 INFO    Thread-109 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 12:05:05,582 INFO    Thread-109 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 12:05:05,584 INFO    Thread-109 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 12:05:05,588 INFO    Thread-109 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 12:05:05,593 INFO    Thread-109 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_120505-9o1q06oj/logs/debug.log
2025-02-28 12:05:05,598 INFO    Thread-109 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_120505-9o1q06oj/logs/debug-internal.log
2025-02-28 12:05:05,603 INFO    Thread-109 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 12:05:05,609 INFO    Thread-109 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'glorot_uniform'}
config: {'_wandb': {}}
2025-02-28 12:05:05,614 INFO    Thread-109 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 12:05:05,619 ERROR   Thread-109 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 12:05:05,645 INFO    Thread-109 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:02:42,029 INFO    MainThread:212809 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=50
2025-02-28 16:02:43,074 INFO    Thread-111 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:02:43,076 INFO    Thread-111 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:02:43,078 INFO    Thread-111 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:02:43,079 INFO    Thread-111 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:02:43,080 INFO    Thread-111 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:02:43,081 INFO    Thread-111 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_160243-4z2s3il7/logs/debug.log
2025-02-28 16:02:43,082 INFO    Thread-111 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_160243-4z2s3il7/logs/debug-internal.log
2025-02-28 16:02:43,082 INFO    Thread-111 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:02:43,083 INFO    Thread-111 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'nesterov', 'weight_decay': 0, 'weight_init': 'random_normal'}
config: {'_wandb': {}}
2025-02-28 16:02:43,084 INFO    Thread-111 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:02:43,084 ERROR   Thread-111 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:02:43,088 INFO    Thread-111 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:02:53,129 INFO    Thread-112 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:02:53,131 INFO    Thread-112 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:02:53,132 INFO    Thread-112 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:02:53,133 INFO    Thread-112 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:02:53,134 INFO    Thread-112 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:02:53,136 INFO    Thread-112 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_160253-yhnfvbe7/logs/debug.log
2025-02-28 16:02:53,137 INFO    Thread-112 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_160253-yhnfvbe7/logs/debug-internal.log
2025-02-28 16:02:53,138 INFO    Thread-112 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:02:53,139 INFO    Thread-112 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'glorot_uniform'}
config: {'_wandb': {}}
2025-02-28 16:02:53,140 INFO    Thread-112 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:02:53,141 ERROR   Thread-112 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:02:53,145 INFO    Thread-112 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:02:54,223 INFO    Thread-113 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:02:54,224 INFO    Thread-113 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:02:54,226 INFO    Thread-113 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:02:54,228 INFO    Thread-113 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:02:54,230 INFO    Thread-113 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:02:54,231 INFO    Thread-113 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_160254-v1leh5gp/logs/debug.log
2025-02-28 16:02:54,231 INFO    Thread-113 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_160254-v1leh5gp/logs/debug-internal.log
2025-02-28 16:02:54,232 INFO    Thread-113 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:02:54,232 INFO    Thread-113 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'nesterov', 'weight_decay': 0.0005, 'weight_init': 'random_normal'}
config: {'_wandb': {}}
2025-02-28 16:02:54,233 INFO    Thread-113 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:02:54,233 ERROR   Thread-113 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:02:54,236 INFO    Thread-113 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:12:41,093 INFO    MainThread:212809 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=10
2025-02-28 16:12:42,133 INFO    Thread-115 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:12:42,134 INFO    Thread-115 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:12:42,136 INFO    Thread-115 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:12:42,136 INFO    Thread-115 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:12:42,137 INFO    Thread-115 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:12:42,139 INFO    Thread-115 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161242-ubk9u3gt/logs/debug.log
2025-02-28 16:12:42,140 INFO    Thread-115 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161242-ubk9u3gt/logs/debug-internal.log
2025-02-28 16:12:42,141 INFO    Thread-115 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:12:42,141 INFO    Thread-115 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:12:42,142 INFO    Thread-115 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:12:42,142 ERROR   Thread-115 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:12:42,146 INFO    Thread-115 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:12:52,184 INFO    Thread-116 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:12:52,185 INFO    Thread-116 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:12:52,185 INFO    Thread-116 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:12:52,186 INFO    Thread-116 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:12:52,187 INFO    Thread-116 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:12:52,187 INFO    Thread-116 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161252-6krif7lv/logs/debug.log
2025-02-28 16:12:52,188 INFO    Thread-116 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161252-6krif7lv/logs/debug-internal.log
2025-02-28 16:12:52,189 INFO    Thread-116 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:12:52,189 INFO    Thread-116 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:12:52,190 INFO    Thread-116 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:12:52,190 ERROR   Thread-116 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:12:52,194 INFO    Thread-116 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:12:53,000 INFO    Thread-117 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:12:53,001 INFO    Thread-117 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:12:53,002 INFO    Thread-117 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:12:53,003 INFO    Thread-117 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:12:53,005 INFO    Thread-117 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:12:53,006 INFO    Thread-117 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161252-heqcxuex/logs/debug.log
2025-02-28 16:12:53,007 INFO    Thread-117 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161252-heqcxuex/logs/debug-internal.log
2025-02-28 16:12:53,008 INFO    Thread-117 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:12:53,009 INFO    Thread-117 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'rmsprop', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:12:53,010 INFO    Thread-117 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:12:53,010 ERROR   Thread-117 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:12:53,014 INFO    Thread-117 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:13:03,045 INFO    Thread-118 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:13:03,045 INFO    Thread-118 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:13:03,046 INFO    Thread-118 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:13:03,047 INFO    Thread-118 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:13:03,047 INFO    Thread-118 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:13:03,048 INFO    Thread-118 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161303-dkmnt2pm/logs/debug.log
2025-02-28 16:13:03,048 INFO    Thread-118 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161303-dkmnt2pm/logs/debug-internal.log
2025-02-28 16:13:03,049 INFO    Thread-118 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:13:03,049 INFO    Thread-118 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 4, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:13:03,050 INFO    Thread-118 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:13:03,050 ERROR   Thread-118 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:13:03,054 INFO    Thread-118 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:13:04,037 INFO    Thread-119 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:13:04,038 INFO    Thread-119 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:13:04,039 INFO    Thread-119 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:13:04,040 INFO    Thread-119 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:13:04,041 INFO    Thread-119 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:13:04,041 INFO    Thread-119 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161304-tdi3d5b6/logs/debug.log
2025-02-28 16:13:04,042 INFO    Thread-119 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161304-tdi3d5b6/logs/debug-internal.log
2025-02-28 16:13:04,042 INFO    Thread-119 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:13:04,043 INFO    Thread-119 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:13:04,043 INFO    Thread-119 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:13:04,044 ERROR   Thread-119 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:13:04,047 INFO    Thread-119 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:13:14,075 INFO    Thread-120 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:13:14,078 INFO    Thread-120 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:13:14,080 INFO    Thread-120 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:13:14,081 INFO    Thread-120 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:13:14,083 INFO    Thread-120 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:13:14,084 INFO    Thread-120 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161314-2i0kft8b/logs/debug.log
2025-02-28 16:13:14,085 INFO    Thread-120 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161314-2i0kft8b/logs/debug-internal.log
2025-02-28 16:13:14,087 INFO    Thread-120 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:13:14,088 INFO    Thread-120 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:13:14,089 INFO    Thread-120 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:13:14,091 ERROR   Thread-120 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:13:14,095 INFO    Thread-120 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:13:14,869 INFO    Thread-121 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:13:14,871 INFO    Thread-121 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:13:14,872 INFO    Thread-121 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:13:14,873 INFO    Thread-121 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:13:14,876 INFO    Thread-121 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:13:14,879 INFO    Thread-121 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161314-67n7snlk/logs/debug.log
2025-02-28 16:13:14,880 INFO    Thread-121 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161314-67n7snlk/logs/debug-internal.log
2025-02-28 16:13:14,881 INFO    Thread-121 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:13:14,883 INFO    Thread-121 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:13:14,884 INFO    Thread-121 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:13:14,885 ERROR   Thread-121 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:13:14,891 INFO    Thread-121 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:13:24,928 INFO    Thread-122 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:13:24,929 INFO    Thread-122 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:13:24,931 INFO    Thread-122 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:13:24,932 INFO    Thread-122 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:13:24,934 INFO    Thread-122 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:13:24,935 INFO    Thread-122 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161324-2b3c6ehy/logs/debug.log
2025-02-28 16:13:24,936 INFO    Thread-122 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161324-2b3c6ehy/logs/debug-internal.log
2025-02-28 16:13:24,938 INFO    Thread-122 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:13:24,939 INFO    Thread-122 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:13:24,940 INFO    Thread-122 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:13:24,942 ERROR   Thread-122 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:13:24,947 INFO    Thread-122 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:13:26,158 INFO    Thread-123 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:13:26,160 INFO    Thread-123 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:13:26,162 INFO    Thread-123 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:13:26,163 INFO    Thread-123 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:13:26,164 INFO    Thread-123 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:13:26,166 INFO    Thread-123 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161326-tnv7b8k2/logs/debug.log
2025-02-28 16:13:26,167 INFO    Thread-123 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161326-tnv7b8k2/logs/debug-internal.log
2025-02-28 16:13:26,168 INFO    Thread-123 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:13:26,169 INFO    Thread-123 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:13:26,171 INFO    Thread-123 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:13:26,172 ERROR   Thread-123 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:13:26,177 INFO    Thread-123 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:13:36,205 INFO    Thread-124 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:13:36,206 INFO    Thread-124 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:13:36,207 INFO    Thread-124 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:13:36,208 INFO    Thread-124 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:13:36,208 INFO    Thread-124 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:13:36,209 INFO    Thread-124 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161336-ikk3g8h2/logs/debug.log
2025-02-28 16:13:36,210 INFO    Thread-124 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161336-ikk3g8h2/logs/debug-internal.log
2025-02-28 16:13:36,210 INFO    Thread-124 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:13:36,211 INFO    Thread-124 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:13:36,212 INFO    Thread-124 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:13:36,213 ERROR   Thread-124 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:13:36,217 INFO    Thread-124 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:15:36,306 INFO    MainThread:212809 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=10
2025-02-28 16:15:37,256 INFO    Thread-134 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:15:37,259 INFO    Thread-134 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:15:37,262 INFO    Thread-134 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:15:37,264 INFO    Thread-134 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:15:37,265 INFO    Thread-134 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:15:37,268 INFO    Thread-134 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161537-1x3f7zb7/logs/debug.log
2025-02-28 16:15:37,269 INFO    Thread-134 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161537-1x3f7zb7/logs/debug-internal.log
2025-02-28 16:15:37,270 INFO    Thread-134 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:15:37,272 INFO    Thread-134 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:15:37,273 INFO    Thread-134 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:15:37,274 ERROR   Thread-134 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:15:37,278 INFO    Thread-134 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:15:47,303 INFO    Thread-135 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:15:47,303 INFO    Thread-135 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:15:47,304 INFO    Thread-135 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:15:47,305 INFO    Thread-135 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:15:47,305 INFO    Thread-135 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:15:47,306 INFO    Thread-135 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161547-z7ll4227/logs/debug.log
2025-02-28 16:15:47,306 INFO    Thread-135 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161547-z7ll4227/logs/debug-internal.log
2025-02-28 16:15:47,307 INFO    Thread-135 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:15:47,308 INFO    Thread-135 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:15:47,309 INFO    Thread-135 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:15:47,309 ERROR   Thread-135 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:15:47,313 INFO    Thread-135 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:15:48,520 INFO    Thread-136 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:15:48,522 INFO    Thread-136 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:15:48,523 INFO    Thread-136 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:15:48,524 INFO    Thread-136 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:15:48,525 INFO    Thread-136 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:15:48,526 INFO    Thread-136 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161548-fdxkeomz/logs/debug.log
2025-02-28 16:15:48,527 INFO    Thread-136 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161548-fdxkeomz/logs/debug-internal.log
2025-02-28 16:15:48,528 INFO    Thread-136 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:15:48,528 INFO    Thread-136 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:15:48,529 INFO    Thread-136 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:15:48,529 ERROR   Thread-136 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:15:48,533 INFO    Thread-136 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:15:58,568 INFO    Thread-137 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:15:58,570 INFO    Thread-137 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:15:58,571 INFO    Thread-137 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:15:58,572 INFO    Thread-137 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:15:58,573 INFO    Thread-137 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:15:58,574 INFO    Thread-137 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161558-2tbgnsit/logs/debug.log
2025-02-28 16:15:58,575 INFO    Thread-137 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161558-2tbgnsit/logs/debug-internal.log
2025-02-28 16:15:58,575 INFO    Thread-137 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:15:58,576 INFO    Thread-137 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:15:58,576 INFO    Thread-137 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:15:58,577 ERROR   Thread-137 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:15:58,580 INFO    Thread-137 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:15:59,784 INFO    Thread-138 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:15:59,786 INFO    Thread-138 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:15:59,788 INFO    Thread-138 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:15:59,789 INFO    Thread-138 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:15:59,789 INFO    Thread-138 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:15:59,790 INFO    Thread-138 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161559-rekmeh09/logs/debug.log
2025-02-28 16:15:59,790 INFO    Thread-138 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161559-rekmeh09/logs/debug-internal.log
2025-02-28 16:15:59,791 INFO    Thread-138 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:15:59,792 INFO    Thread-138 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:15:59,792 INFO    Thread-138 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:15:59,793 ERROR   Thread-138 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:15:59,796 INFO    Thread-138 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:16:09,841 INFO    Thread-139 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:16:09,843 INFO    Thread-139 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:16:09,843 INFO    Thread-139 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:16:09,844 INFO    Thread-139 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:16:09,845 INFO    Thread-139 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:16:09,846 INFO    Thread-139 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161609-rxp5xqzi/logs/debug.log
2025-02-28 16:16:09,846 INFO    Thread-139 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161609-rxp5xqzi/logs/debug-internal.log
2025-02-28 16:16:09,847 INFO    Thread-139 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:16:09,847 INFO    Thread-139 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'rmsprop', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:16:09,848 INFO    Thread-139 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:16:09,849 ERROR   Thread-139 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:16:09,852 INFO    Thread-139 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:16:11,248 INFO    Thread-140 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:16:11,249 INFO    Thread-140 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:16:11,251 INFO    Thread-140 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:16:11,252 INFO    Thread-140 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:16:11,252 INFO    Thread-140 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:16:11,253 INFO    Thread-140 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161611-rrjkqfcx/logs/debug.log
2025-02-28 16:16:11,254 INFO    Thread-140 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161611-rrjkqfcx/logs/debug-internal.log
2025-02-28 16:16:11,254 INFO    Thread-140 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:16:11,255 INFO    Thread-140 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:16:11,255 INFO    Thread-140 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:16:11,256 ERROR   Thread-140 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:16:11,260 INFO    Thread-140 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:16:21,290 INFO    Thread-141 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:16:21,291 INFO    Thread-141 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:16:21,292 INFO    Thread-141 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:16:21,292 INFO    Thread-141 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:16:21,293 INFO    Thread-141 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:16:21,294 INFO    Thread-141 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161621-3w2cfs6s/logs/debug.log
2025-02-28 16:16:21,295 INFO    Thread-141 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161621-3w2cfs6s/logs/debug-internal.log
2025-02-28 16:16:21,296 INFO    Thread-141 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:16:21,296 INFO    Thread-141 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:16:21,297 INFO    Thread-141 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:16:21,298 ERROR   Thread-141 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:16:21,301 INFO    Thread-141 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:16:22,560 INFO    Thread-142 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:16:22,561 INFO    Thread-142 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:16:22,561 INFO    Thread-142 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:16:22,562 INFO    Thread-142 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:16:22,562 INFO    Thread-142 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:16:22,563 INFO    Thread-142 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161622-bwgiqoul/logs/debug.log
2025-02-28 16:16:22,564 INFO    Thread-142 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161622-bwgiqoul/logs/debug-internal.log
2025-02-28 16:16:22,565 INFO    Thread-142 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:16:22,565 INFO    Thread-142 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:16:22,566 INFO    Thread-142 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:16:22,567 ERROR   Thread-142 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:16:22,570 INFO    Thread-142 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:16:32,611 INFO    Thread-143 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:16:32,613 INFO    Thread-143 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:16:32,615 INFO    Thread-143 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:16:32,616 INFO    Thread-143 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:16:32,618 INFO    Thread-143 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:16:32,619 INFO    Thread-143 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161632-4bi8tqbr/logs/debug.log
2025-02-28 16:16:32,621 INFO    Thread-143 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_161632-4bi8tqbr/logs/debug-internal.log
2025-02-28 16:16:32,623 INFO    Thread-143 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:16:32,624 INFO    Thread-143 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:16:32,625 INFO    Thread-143 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:16:32,627 ERROR   Thread-143 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:16:32,630 INFO    Thread-143 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:20:30,052 INFO    MainThread:212809 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=10
2025-02-28 16:20:31,273 INFO    Thread-145 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:20:31,275 INFO    Thread-145 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:20:31,277 INFO    Thread-145 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:20:31,279 INFO    Thread-145 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:20:31,281 INFO    Thread-145 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:20:31,283 INFO    Thread-145 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162031-d3bw4wcy/logs/debug.log
2025-02-28 16:20:31,285 INFO    Thread-145 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162031-d3bw4wcy/logs/debug-internal.log
2025-02-28 16:20:31,287 INFO    Thread-145 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:20:31,288 INFO    Thread-145 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:20:31,289 INFO    Thread-145 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:20:31,289 ERROR   Thread-145 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:20:31,295 INFO    Thread-145 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:20:41,325 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:20:41,327 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:20:41,328 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:20:41,329 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:20:41,330 INFO    Thread-146 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:20:41,331 INFO    Thread-146 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162041-z9vxru34/logs/debug.log
2025-02-28 16:20:41,331 INFO    Thread-146 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162041-z9vxru34/logs/debug-internal.log
2025-02-28 16:20:41,332 INFO    Thread-146 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:20:41,333 INFO    Thread-146 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:20:41,333 INFO    Thread-146 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:20:41,334 ERROR   Thread-146 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:20:41,338 INFO    Thread-146 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:20:42,471 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:20:42,473 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:20:42,475 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:20:42,476 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:20:42,477 INFO    Thread-147 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:20:42,477 INFO    Thread-147 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162042-hdupjbre/logs/debug.log
2025-02-28 16:20:42,478 INFO    Thread-147 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162042-hdupjbre/logs/debug-internal.log
2025-02-28 16:20:42,479 INFO    Thread-147 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:20:42,479 INFO    Thread-147 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 4, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:20:42,480 INFO    Thread-147 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:20:42,481 ERROR   Thread-147 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:20:42,485 INFO    Thread-147 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:20:52,523 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:20:52,524 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:20:52,525 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:20:52,526 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:20:52,526 INFO    Thread-148 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:20:52,527 INFO    Thread-148 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162052-l99lelfm/logs/debug.log
2025-02-28 16:20:52,528 INFO    Thread-148 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162052-l99lelfm/logs/debug-internal.log
2025-02-28 16:20:52,529 INFO    Thread-148 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:20:52,529 INFO    Thread-148 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:20:52,530 INFO    Thread-148 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:20:52,531 ERROR   Thread-148 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:20:52,535 INFO    Thread-148 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:20:53,950 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:20:53,951 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:20:53,952 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:20:53,953 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:20:53,954 INFO    Thread-149 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:20:53,954 INFO    Thread-149 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162053-5ohubwwi/logs/debug.log
2025-02-28 16:20:53,955 INFO    Thread-149 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162053-5ohubwwi/logs/debug-internal.log
2025-02-28 16:20:53,955 INFO    Thread-149 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:20:53,956 INFO    Thread-149 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:20:53,957 INFO    Thread-149 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:20:53,957 ERROR   Thread-149 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:20:53,961 INFO    Thread-149 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:03,984 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:03,986 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:03,987 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:03,989 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:03,991 INFO    Thread-150 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:03,993 INFO    Thread-150 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162103-stubywf6/logs/debug.log
2025-02-28 16:21:03,994 INFO    Thread-150 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162103-stubywf6/logs/debug-internal.log
2025-02-28 16:21:03,996 INFO    Thread-150 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:03,997 INFO    Thread-150 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:21:03,997 INFO    Thread-150 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:03,998 ERROR   Thread-150 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:04,003 INFO    Thread-150 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:05,119 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:05,121 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:05,122 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:05,124 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:05,125 INFO    Thread-151 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:05,127 INFO    Thread-151 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162105-ivbsb743/logs/debug.log
2025-02-28 16:21:05,128 INFO    Thread-151 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162105-ivbsb743/logs/debug-internal.log
2025-02-28 16:21:05,129 INFO    Thread-151 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:05,129 INFO    Thread-151 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:21:05,130 INFO    Thread-151 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:05,131 ERROR   Thread-151 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:05,134 INFO    Thread-151 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:15,154 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:15,156 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:15,157 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:15,159 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:15,161 INFO    Thread-152 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:15,162 INFO    Thread-152 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162115-l1shtv9b/logs/debug.log
2025-02-28 16:21:15,164 INFO    Thread-152 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162115-l1shtv9b/logs/debug-internal.log
2025-02-28 16:21:15,165 INFO    Thread-152 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:15,167 INFO    Thread-152 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-02-28 16:21:15,167 INFO    Thread-152 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:15,168 ERROR   Thread-152 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:15,171 INFO    Thread-152 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:16,271 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:16,273 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:16,276 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:16,278 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:16,279 INFO    Thread-153 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:16,281 INFO    Thread-153 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162116-go1ugzmr/logs/debug.log
2025-02-28 16:21:16,282 INFO    Thread-153 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162116-go1ugzmr/logs/debug-internal.log
2025-02-28 16:21:16,282 INFO    Thread-153 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:16,283 INFO    Thread-153 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:21:16,284 INFO    Thread-153 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:16,284 ERROR   Thread-153 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:16,288 INFO    Thread-153 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
2025-02-28 16:21:26,314 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:26,316 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:26,319 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:26,320 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:26,321 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:26,322 INFO    Thread-154 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162126-gg05qhe6/logs/debug.log
2025-02-28 16:21:26,322 INFO    Thread-154 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162126-gg05qhe6/logs/debug-internal.log
2025-02-28 16:21:26,323 INFO    Thread-154 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:26,324 INFO    Thread-154 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:21:26,324 INFO    Thread-154 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:26,325 ERROR   Thread-154 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:26,329 INFO    Thread-154 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
