2025-02-28 16:21:26,314 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-28 16:21:26,316 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Configure stats pid to 212809
2025-02-28 16:21:26,319 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-02-28 16:21:26,320 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-02-28 16:21:26,321 INFO    Thread-154 (_run_job):212809 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-28 16:21:26,322 INFO    Thread-154 (_run_job):212809 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162126-gg05qhe6/logs/debug.log
2025-02-28 16:21:26,322 INFO    Thread-154 (_run_job):212809 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250228_162126-gg05qhe6/logs/debug-internal.log
2025-02-28 16:21:26,323 INFO    Thread-154 (_run_job):212809 [wandb_init.py:init():761] calling init triggers
2025-02-28 16:21:26,324 INFO    Thread-154 (_run_job):212809 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-02-28 16:21:26,324 INFO    Thread-154 (_run_job):212809 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-28 16:21:26,325 ERROR   Thread-154 (_run_job):212809 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-02-28 16:21:26,329 INFO    Thread-154 (_run_job):212809 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/i3a0s7di
